# Generated by Django 6.0.2 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='patient_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
