# Generated by Django 6.0.2 on 2026-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_medicalimage_patient_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptiontoken',
            name='token',
        ),
        migrations.AddField(
            model_name='decryptiontoken',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decryptiontoken',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
