# Generated by Django 6.0.2 on 2026-03-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_decryptiontoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
