# Generated by Django 6.0.2 on 2026-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_remove_medicalimage_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='final_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
