# Generated by Django 6.0.2 on 2026-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_medicalimage_final_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
