# Generated by Django 6.0.2 on 2026-03-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_medicalimage_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalimage',
            name='patient_key',
        ),
        migrations.RemoveField(
            model_name='medicalimage',
            name='public_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_report', models.BinaryField()),
                ('encrypted_aes_key', models.BinaryField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.medicalimage')),
            ],
        ),
    ]
