# Generated by Django 6.0.2 on 2026-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_remove_medicalimage_patient_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
