# Generated by Django 6.0.2 on 2026-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_report_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
