# Generated by Django 6.0.2 on 2026-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_alter_userprofile_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='image_type',
            field=models.CharField(default='image/png', max_length=50),
        ),
    ]
