# Generated by Django 6.0.2 on 2026-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_medicalimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
