# Generated by Django 6.0.2 on 2026-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_report_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='final_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='image_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='image_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
    ]
