# Generated by Django 6.0.2 on 2026-03-31 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0014_alter_medicalimage_final_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicalimage',
            index=models.Index(fields=['user'], name='detection_m_user_id_f88a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalimage',
            index=models.Index(fields=['assigned_doctor'], name='detection_m_assigne_304743_idx'),
        ),
    ]
