# Generated by Django 6.0.2 on 2026-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_medicalimage_prescription_report_payment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('severe', 'Severe')], default='mild', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
