# Generated by Django 6.0.2 on 2026-04-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0018_report_severity_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='available_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='is_available',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='time',
            field=models.TimeField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['doctor'], name='detection_d_doctor__2b87ae_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['date'], name='detection_d_date_74b96e_idx'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
