# Generated by Django 6.0.2 on 2026-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
