# Generated by Django 6.0.2 on 2026-04-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0020_alter_doctoravailability_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='time',
        ),
    ]
