# Generated by Django 6.0.2 on 2026-04-05 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0021_remove_doctoravailability_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot',
            field=models.CharField(choices=[('9AM-10AM', '9AM-10AM'), ('10AM-11AM', '10AM-11AM'), ('11AM-12PM', '11AM-12PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM')], default='00.00', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date', 'slot')},
        ),
    ]
