# Generated by Django 6.0.2 on 2026-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0022_doctoravailability_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.TextField()),
                ('encrypted_key', models.TextField()),
                ('signature', models.TextField()),
                ('hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='doctoravailability',
            name='detection_d_doctor__2b87ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctoravailability',
            name='detection_d_date_74b96e_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalimage',
            name='detection_m_user_id_f88a3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalimage',
            name='detection_m_assigne_304743_idx',
        ),
    ]
