# Generated by Django 6.0.2 on 2026-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0023_securereport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecureReport',
        ),
        migrations.AddField(
            model_name='report',
            name='report_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(default='mild', max_length=10),
        ),
    ]
