# Generated by Django 6.0.2 on 2026-04-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0024_delete_securereport_report_report_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='patient_encrypted_aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
